import type { Task } from "./data";
import { employees } from "./data";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "../ui/dialog";
import { Button } from "../ui/button";
import { AppAvatar } from "./AppAvatar";
import { WorkloadDot } from "./WorkloadDot";
export function TaskDetailsModal({ task, open, onOpenChange, onDelegate }: { task: Task | null; open: boolean; onOpenChange: (open: boolean) => void; onDelegate: () => void }) {
  if (!task) return null; const person = task.assigneeData ?? employees.find((p) => p.id === task.assignee) ?? employees[0];
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{task.title}</DialogTitle></DialogHeader><div className="grid gap-5"><div className="grid gap-3 rounded-xl bg-bg-faint p-4 sm:grid-cols-3"><div><div className="text-[10px] uppercase text-muted-foreground">Status</div><div className="mt-1 text-sm font-medium">{task.status}</div></div><div><div className="text-[10px] uppercase text-muted-foreground">Priority</div><div className="mt-1 text-sm font-medium capitalize">{task.priority}</div></div><div><div className="text-[10px] uppercase text-muted-foreground">Deadline</div><div className="mt-1 text-sm font-medium">{task.deadline}</div></div></div><div><div className="mb-2 text-sm font-semibold">Assignee</div><div className="flex items-center gap-3"><AppAvatar initials={person.initials}/><div><div className="text-sm font-medium">{person.name}</div><div className="flex items-center gap-1.5 text-xs text-muted-foreground"><WorkloadDot workload={person.workload}/>{person.title}</div></div></div></div><div><div className="mb-2 text-sm font-semibold">Description</div><p className="text-sm leading-6 text-muted-foreground">{task.description || <>Coordinate delivery for {task.project}. Keep dependencies visible, update progress as work moves, and attach completion notes before closing.</>}</p></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button><Button className="bg-brand-primary text-white" onClick={() => { onOpenChange(false); onDelegate(); }}>Delegate Sub-task</Button></DialogFooter></DialogContent></Dialog>;
}
