import { useEffect, useState } from "react";
import { ArrowUpRight, Building2, CheckCircle2, FolderKanban, ShieldCheck, Users } from "lucide-react";
import { Button } from "../../ui/button";
import { AvatarStack } from "../AvatarStack";
import { employees as fallbackEmployees, type Employee } from "../data";
import { getEmployees } from "../../../lib/api";
import type { ScreenId } from "../AppShell";

const workspaces = [{ name: "Project Alpha", admin: "Arif Hossain", projects: 5, health: 89, status: "Active" }, { name: "Growth Workspace", admin: "Mahin Rahman", projects: 4, health: 94, status: "Active" }, { name: "Checkout Team", admin: "Sadia Karim", projects: 3, health: 77, status: "Attention" }, { name: "Platform", admin: "Arif Hossain", projects: 6, health: 92, status: "Active" }];
export function SuperAdminScreen({ onNavigate }: { onNavigate?: (id: ScreenId) => void }) {
  const [employees, setEmployees] = useState<Employee[]>(fallbackEmployees);
  useEffect(() => { getEmployees().then(setEmployees).catch(() => setEmployees(fallbackEmployees)); }, []);
  const cards = [[Building2, "Workspaces", "4", "All operating normally"], [FolderKanban, "Projects", "18", "13 active"], [Users, "Employees", "76", "Across 4 workspaces"], [ShieldCheck, "Admins", "6", "2 invited this month"]] as const;
  return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="tdts-page-title">Company Overview</h1><p className="mt-1 text-sm text-muted-foreground">Company-wide delivery signals without entering individual workspaces.</p></div><Button variant="outline" onClick={() => onNavigate?.("sa-projects")}>View all projects<ArrowUpRight /></Button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon, label, value, detail]) => <div key={label} className="tdts-card p-4"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-tertiary text-brand-primary"><Icon className="h-4 w-4" /></span><div className="tdts-tabular mt-4 text-2xl font-semibold">{value}</div><div className="text-sm font-medium">{label}</div><div className="mt-1 text-xs text-muted-foreground">{detail}</div></div>)}</div><section className="tdts-card mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-border-primary p-4"><div><h2 className="tdts-heading">Active Workspaces</h2><p className="text-xs text-muted-foreground">Health, ownership and project volume</p></div><AvatarStack people={employees.map((employee) => ({ initials: employee.initials, name: employee.name }))} /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-bg-faint text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">Workspace</th><th className="px-4 py-3">Admin</th><th className="px-4 py-3">Projects</th><th className="px-4 py-3">Health</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{workspaces.map((workspace) => <tr key={workspace.name} className="border-t border-border-secondary"><td className="px-4 py-3 font-medium">{workspace.name}</td><td className="px-4 py-3">{workspace.admin}</td><td className="px-4 py-3">{workspace.projects}</td><td className="px-4 py-3"><span className="tdts-tabular font-semibold">{workspace.health}%</span></td><td className="px-4 py-3"><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs ${workspace.status === "Active" ? "bg-emerald-500/10 text-emerald-600" : "bg-amber-500/10 text-amber-600"}`}><CheckCircle2 className="h-3 w-3" />{workspace.status}</span></td></tr>)}</tbody></table></div></section></div>;
}
